# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0002_auto_20171129_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='imgs',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
