# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0006_auto_20171207_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topgames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('imgs', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='img',
        ),
        migrations.AddField(
            model_name='reviews',
            name='imgs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(max_length=12),
        ),
    ]
