# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0008_reviews_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='imgs',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='info',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
