# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0009_auto_20171214_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='imgs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='info',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
