# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0010_auto_20171214_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='imgs',
        ),
    ]
