# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0013_reviews_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='imgs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
