# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0014_auto_20171219_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='imgs',
            field=models.CharField(max_length=500),
        ),
    ]
