# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0017_auto_20171219_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
    ]
