# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0018_remove_news_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='imgs',
        ),
    ]
