# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0021_remove_reviews_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='imgs',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
