# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0022_reviews_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
