# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0024_auto_20171219_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='owner',
        ),
    ]
