# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0028_news_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='info',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
