# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0033_auto_20171219_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imgs',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='topgames',
            name='imgs',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
