# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0036_auto_20171219_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='category',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
