# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0038_topgames_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
