# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0039_auto_20171228_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='topgames',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
