# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0040_auto_20171228_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='info',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
