# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0041_auto_20171228_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='cpu',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='gpu',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='os',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='ram',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='space',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
