# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0042_auto_20171229_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='cpu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='gpu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='os',
            field=models.CharField(max_length=200),
        ),
    ]
