# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0043_auto_20171229_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topgames',
            name='release_date',
            field=models.CharField(max_length=50),
        ),
    ]
