# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0044_auto_20180102_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='gameplay',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
