# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0045_reviews_gameplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='gameplay',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='imgs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
