# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamereviews', '0047_slideshow'),
        ('comments', '0006_remove_comment_gamereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gamereview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamereviews.Reviews'),
        ),
    ]
