# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_remove_comment_gamereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
    ]
